# Generated by Django 4.1.2 on 2022-10-30 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_web', '0002_memberorder_memberorderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberorder',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='memberorderitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='memberorderitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
